# Generated by Django 6.0.3 on 2026-03-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('first_names', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('place_of_birth', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['surname', 'first_names'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='dashboard.faculty')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('faculty', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='dashboard.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('student_internal_id', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('carrying', models.PositiveIntegerField(default=0)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='dashboard.academicperiod')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='dashboard.programme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='dashboard.student')),
            ],
            options={
                'ordering': ['student__surname', 'student__first_names'],
                'unique_together': {('student', 'period', 'programme')},
            },
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_type', models.CharField(blank=True, max_length=100)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grading_rule', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='dashboard.course')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to='dashboard.registration')),
            ],
            options={
                'ordering': ['course__code'],
                'unique_together': {('registration', 'course')},
            },
        ),
    ]
