# Generated by Django 6.0.3 on 2026-04-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='source_row_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompletionAnalysisImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(db_index=True, max_length=30)),
                ('student_name', models.CharField(blank=True, max_length=255)),
                ('programme_name', models.CharField(blank=True, max_length=255)),
                ('academic_stage', models.CharField(blank=True, max_length=100)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('effective_cohort', models.CharField(blank=True, max_length=255)),
                ('original_cohort', models.CharField(blank=True, max_length=255)),
                ('shifted_label', models.CharField(blank=True, max_length=20)),
                ('shifted', models.BooleanField(default=False)),
                ('zero_completion_reason', models.CharField(blank=True, max_length=255)),
                ('completion_rate_display', models.CharField(blank=True, max_length=20)),
                ('completion_rate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_import_rows', to='dashboard.programme')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_import_rows', to='dashboard.student')),
            ],
            options={
                'ordering': ['programme_name', 'registration_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseMarkImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(db_index=True, max_length=20)),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('period_name', models.CharField(blank=True, max_length=255)),
                ('period_external_id', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(db_index=True, max_length=30)),
                ('programme_code', models.CharField(blank=True, max_length=20)),
                ('programme_name', models.CharField(blank=True, max_length=255)),
                ('attendance_type', models.CharField(blank=True, max_length=100)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grading_rule', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_import_rows', to='dashboard.course')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_import_rows', to='dashboard.registration')),
            ],
            options={
                'ordering': ['registration_number', 'period_name', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row_id', models.PositiveIntegerField(unique=True)),
                ('registration_number', models.CharField(db_index=True, max_length=30)),
                ('first_names', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('programme_external_id', models.PositiveIntegerField(blank=True, null=True)),
                ('programme_code', models.CharField(blank=True, max_length=20)),
                ('programme_name', models.CharField(blank=True, max_length=255)),
                ('faculty_name', models.CharField(blank=True, max_length=255)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('place_of_birth', models.CharField(blank=True, max_length=255)),
                ('student_internal_id', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_external_id', models.PositiveIntegerField(blank=True, null=True)),
                ('period_external_id', models.PositiveIntegerField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('period_name', models.CharField(blank=True, max_length=255)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('carrying', models.PositiveIntegerField(default=0)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='dashboard.registration')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_import_rows', to='dashboard.student')),
            ],
            options={
                'ordering': ['registration_number', 'period_name'],
            },
        ),
    ]
