# Generated by Django 6.0.3 on 2026-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_registration_source_row_id_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='source_row_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationimportrecord',
            name='source_row_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
