# Generated by Django 6.0.3 on 2026-04-19 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_registration_source_row_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('normalized_key', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('normalized_key', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sort_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ZeroCompletionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.RemoveField(
            model_name='coursemarkimportrecord',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursemarkimportrecord',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='registrationimportrecord',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='registrationimportrecord',
            name='student',
        ),
        migrations.AddField(
            model_name='registration',
            name='decision_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='dashboard.academicdecision'),
        ),
        migrations.AddField(
            model_name='courseresult',
            name='attendance_type_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_results', to='dashboard.attendancetype'),
        ),
        migrations.AddField(
            model_name='registration',
            name='attendance_type_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='dashboard.attendancetype'),
        ),
        migrations.CreateModel(
            name='CompletionAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_stage', models.CharField(blank=True, max_length=100)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('shifted', models.BooleanField(default=False)),
                ('completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_analysis_records', to='dashboard.academicdecision')),
                ('effective_cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effective_completion_records', to='dashboard.cohort')),
                ('original_cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_completion_records', to='dashboard.cohort')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_analysis_records', to='dashboard.programme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_analysis_records', to='dashboard.student')),
                ('zero_completion_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_analysis_records', to='dashboard.zerocompletionreason')),
            ],
            options={
                'ordering': ['programme__name', 'student__registration_number'],
                'unique_together': {('student', 'programme', 'academic_stage', 'effective_cohort')},
            },
        ),
        migrations.DeleteModel(
            name='CompletionAnalysisImportRecord',
        ),
        migrations.DeleteModel(
            name='CourseMarkImportRecord',
        ),
        migrations.DeleteModel(
            name='RegistrationImportRecord',
        ),
    ]
