# Generated by Django 6.0.3 on 2026-05-12 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_platformsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('user_created', 'User created'), ('user_activated', 'User activated'), ('user_deactivated', 'User deactivated'), ('lockout_cleared', 'Lockout cleared'), ('ai_provider_changed', 'AI provider changed'), ('login_success', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout')], db_index=True, max_length=50)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['actor_email'], name='audit_log_actor_e_143066_idx')],
            },
        ),
    ]
